//! Node groups — visual grouping of related nodes.
//!
//! Per DIRECTIVE.md §2: reflow has `GraphGroup`, and the editor must
//! render visual groupings of nodes (collapsible / tinted backdrop).
//! Groups are GENERIC over the host's group metadata — a host that
//! doesn't need groups simply never adds any.
//!
//! Rendering: groups draw BEHIND nodes as a soft-fill rounded rect
//! that auto-resizes to encompass their members' bounding boxes,
//! with the group name in the top-left. Hit-test order is members-
//! before-group so clicking a node selects the node, not the group;
//! clicking the group's chrome (header / empty area) selects the
//! group.

use crate::node::NodeId;
use blinc_core::layer::{Color, Rect};
use std::sync::Arc;

/// Stable per-editor group identifier. Generated by the host.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct GroupId(pub Arc<str>);

impl GroupId {
    pub fn new(id: impl Into<Arc<str>>) -> Self {
        Self(id.into())
    }
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<&str> for GroupId {
    fn from(s: &str) -> Self {
        Self(Arc::from(s))
    }
}
impl From<String> for GroupId {
    fn from(s: String) -> Self {
        Self(Arc::from(s))
    }
}
impl From<Arc<str>> for GroupId {
    fn from(s: Arc<str>) -> Self {
        Self(s)
    }
}

/// A named, visually-distinct grouping of nodes. The editor renders a
/// rounded soft-fill rect with a header bar (title + description +
/// inline chrome).
///
/// **Sizing**: by default the rect auto-sizes to the union of member
/// bounding boxes plus the theme's group padding. Set [`bounds`]
/// (via [`Self::with_bounds`]) to pin an explicit size — useful for
/// hand-laid-out canvases or when the host wants to keep a group's
/// footprint stable while members move within it.
///
/// **Collapsed state**: when [`is_collapsed`] is `true`, the editor
/// folds the group into a compact chrome-only rectangle (header +
/// small body, members hidden) — visual sanitization for decluttering
/// busy canvases. Member ports virtualize at the group boundary so
/// connections still terminate visibly; clicking the chrome expands
/// back. Matches Zeal's collapsed-group pattern.
///
/// **Header chrome**: the editor renders edit / delete / collapse-
/// toggle / status affordances in the group header itself; hosts
/// subscribe to the emitted events via the editor's callback API
/// rather than drawing their own buttons.
///
/// `G` is the host's per-group metadata — opaque to the editor.
/// Typical hosts use it to carry a discriminator for which subgraph
/// the group belongs to, an audit timestamp, or a schema version.
#[derive(Debug, Clone)]
pub struct Group<G> {
    pub id: GroupId,
    pub name: String,
    /// Subtitle / description rendered below the name in the header.
    /// `None` = name-only header. Equivalent to Zeal's
    /// `NodeGroup.description`.
    pub description: Option<String>,
    /// Placeholder text shown when `description` is `None` (or empty).
    /// `Some(...)` causes the description row to be reserved in the
    /// header even with no real description, and the placeholder is
    /// painted in a muted colour. Hosts use this to keep an
    /// "Enter a description" hint visible on user-editable groups
    /// after the user clears the description.
    pub description_placeholder: Option<String>,
    /// Member node ids. Order doesn't matter for rendering; the
    /// renderer takes the union of their bboxes when computing
    /// auto-fit. A typical group always has at least one member —
    /// for visual sanitization use [`is_collapsed`] instead of
    /// "stripping members."
    pub members: Vec<NodeId>,
    /// Explicit bounds override — set when the host wants to pin
    /// the group's footprint instead of auto-fitting to members.
    /// `None` = auto-fit; the manual-resize handle in the group
    /// chrome populates this on user drag.
    pub bounds: Option<Rect>,
    /// Override the theme's default group tint. `None` = use the
    /// theme's `group_tint` for this group.
    pub tint: Option<Color>,
    /// Accent colour applied to the group's BORDER stroke and HEADER
    /// bar (not the body fill). When `Some`, overrides
    /// `theme.group_border()` and `theme.group_header_fill()` while
    /// leaving the body backdrop alone. Used by hosts that want to
    /// chrome-mark a group without flooding its interior with colour
    /// — e.g. the subgraph-expansion container in `node_editor_demo`
    /// uses the same warning accent the diamond carries, so the
    /// container reads as "this is an opened subgraph" without
    /// burying its member nodes under a solid fill. `None` = use
    /// theme defaults.
    pub accent: Option<Color>,
    /// **Minimized for visual sanitization.** When `true`, the
    /// renderer folds the group's footprint to a compact chrome-only
    /// rectangle (header + small body), members hidden visually but
    /// still present in the model. Member ports virtualize at the
    /// group boundary so cross-group connections still terminate
    /// visibly (per Zeal's `CollapsedGroupPortHandler` pattern).
    /// The field + chrome toggle are reserved; full member-hiding
    /// and port virtualization land in a follow-up.
    pub is_collapsed: bool,
    /// Optional status badge rendered in the group header (Zeal's
    /// triangle + count chip pattern). `None` = no badge.
    pub badge: Option<StatusBadge>,
    /// Soft-disable flag. Same semantic as
    /// [`crate::NodeInstance::disabled`] but applied at the group
    /// level: every member node inherits the disabled visual (dim +
    /// Pending-style incident edges) AND the group's own chrome
    /// (header bar, body fill, badge) dims. Toggled via the editor's
    /// `D` key shortcut when a group is selected. Defaults to
    /// `false`.
    pub disabled: bool,
    /// Host metadata. The editor never reads this.
    pub metadata: G,
}

impl<G: Default> Group<G> {
    pub fn new(id: impl Into<GroupId>, name: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            name: name.into(),
            description: None,
            description_placeholder: None,
            members: Vec::new(),
            bounds: None,
            tint: None,
            accent: None,
            is_collapsed: false,
            badge: None,
            disabled: false,
            metadata: G::default(),
        }
    }

    /// Append a member node id. Doesn't dedup — the renderer treats
    /// duplicates as harmless (bbox union is idempotent).
    pub fn add_member(mut self, node: impl Into<NodeId>) -> Self {
        self.members.push(node.into());
        self
    }
}

impl<G> Group<G> {
    pub fn with_description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    /// Set a placeholder string painted in the description slot when
    /// `description` is `None` or empty. Use this on user-editable
    /// groups so an empty-description state still shows a hint.
    pub fn with_description_placeholder(mut self, placeholder: impl Into<String>) -> Self {
        self.description_placeholder = Some(placeholder.into());
        self
    }

    pub fn with_tint(mut self, tint: Color) -> Self {
        self.tint = Some(tint);
        self
    }

    /// Set the accent colour applied to the group's BORDER + HEADER
    /// chrome. See [`Self::accent`] for the design rationale (body
    /// fill stays untouched, only chrome carries the colour).
    pub fn with_accent(mut self, accent: Color) -> Self {
        self.accent = Some(accent);
        self
    }

    pub fn with_bounds(mut self, bounds: Rect) -> Self {
        self.bounds = Some(bounds);
        self
    }

    pub fn with_collapsed(mut self, collapsed: bool) -> Self {
        self.is_collapsed = collapsed;
        self
    }

    pub fn with_badge(mut self, badge: StatusBadge) -> Self {
        self.badge = Some(badge);
        self
    }

    pub fn with_metadata(mut self, metadata: G) -> Self {
        self.metadata = metadata;
        self
    }

    /// Flag the group as soft-disabled — see [`Self::disabled`].
    pub fn with_disabled(mut self, disabled: bool) -> Self {
        self.disabled = disabled;
        self
    }
}

// ─────────────────────────────────────────────────────────────────────
// StatusBadge — used by both Group header chrome and Node corner chip
// ─────────────────────────────────────────────────────────────────────

/// Status indicator rendered in a group header or node corner.
/// Mirrors Zeal's triangle + count chip; the editor draws it from
/// the [`BadgeKind`] and optional count.
#[derive(Debug, Clone)]
pub struct StatusBadge {
    pub kind: BadgeKind,
    /// Numeric count to render next to the kind icon. `None` =
    /// icon-only chip (e.g. "this group has a pending validation
    /// issue" without exposing how many).
    pub count: Option<u32>,
    /// Optional tooltip text — surfaced on hover.
    pub tooltip: Option<String>,
}

/// Semantic kind of a status badge. Maps to a colour + glyph in the
/// theme. The set is intentionally small; hosts that need richer
/// classification thread the detail through the tooltip.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BadgeKind {
    /// Neutral count chip — "N items in this group / N traces /
    /// N runs," no semantic alert.
    Info,
    /// Validation issue or runtime warning. Yellow / orange in the
    /// default theme.
    Warning,
    /// Hard error — failed validation, runtime crash, missing
    /// secret. Red in the default theme.
    Error,
    /// Successful state — passed validation, completed run. Green.
    Success,
    /// Currently active / running. Animated pulse in the renderer.
    Running,
}

impl StatusBadge {
    pub fn info(count: u32) -> Self {
        Self {
            kind: BadgeKind::Info,
            count: Some(count),
            tooltip: None,
        }
    }
    pub fn warning(count: u32) -> Self {
        Self {
            kind: BadgeKind::Warning,
            count: Some(count),
            tooltip: None,
        }
    }
    pub fn error(count: u32) -> Self {
        Self {
            kind: BadgeKind::Error,
            count: Some(count),
            tooltip: None,
        }
    }
    pub fn success() -> Self {
        Self {
            kind: BadgeKind::Success,
            count: None,
            tooltip: None,
        }
    }
    pub fn running() -> Self {
        Self {
            kind: BadgeKind::Running,
            count: None,
            tooltip: None,
        }
    }
    pub fn with_tooltip(mut self, tooltip: impl Into<String>) -> Self {
        self.tooltip = Some(tooltip.into());
        self
    }
}

// ─────────────────────────────────────────────────────────────────────
// Group-mutation request events
// ─────────────────────────────────────────────────────────────────────
//
// Editor-emitted requests that the host materialises in its model
// and re-syncs via `set_graph(...)`. The editor itself is a view —
// it does not mutate group membership directly.

/// Fired when the user marquee-selects multiple nodes and triggers
/// the "group these" action (context menu item / keyboard shortcut).
/// Borrowed from Zeal's flow — selection-rect → wrap-in-group is
/// table-stakes for node editors and is wired in the editor's
/// interaction layer.
///
/// The host's handler creates a new [`Group`] with the supplied
/// `members`, picks a fresh [`GroupId`], and re-loads the graph.
/// The editor doesn't pick the id because the host typically wants
/// to namespace it (e.g. `groups/{uuid}`).
#[derive(Debug, Clone)]
pub struct CreateGroupRequest {
    pub members: Vec<NodeId>,
    /// Default name the editor proposes (e.g. `"New Group"`); the
    /// host can rename before / after creation. Hosts that want a
    /// modal name-input flow ignore this and prompt the user.
    pub default_name: String,
}

/// Fired when the user drags a node beyond its parent group's
/// bounds or selects "remove from group" via the node's context
/// menu. Host removes the node id from `group.members` and
/// re-syncs.
#[derive(Debug, Clone)]
pub struct RemoveFromGroupRequest {
    pub group: GroupId,
    pub node: NodeId,
    /// Hint at WHY the request fired — drag-out vs explicit menu.
    /// The host might confirm differently per source (silent for
    /// drag, confirm dialog for menu).
    pub source: RemoveSource,
}

/// Why a [`RemoveFromGroupRequest`] fired.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RemoveSource {
    /// User dragged the node outside the group's content rect.
    DraggedOut,
    /// User picked "remove from group" from the node's context menu
    /// or keyboard shortcut.
    Explicit,
}

/// Fired when the user drags a node INTO a group's content rect
/// (i.e. it wasn't a member; now it is). The host adds the node id
/// to `group.members` and re-syncs.
///
/// Note: dragging an already-member node within its own group is
/// just a move — no event fires.
#[derive(Debug, Clone)]
pub struct AddToGroupRequest {
    pub group: GroupId,
    pub node: NodeId,
}

/// Fired when the user toggles a group's collapsed state via the
/// header chrome's collapse / expand affordance. Host flips
/// `group.is_collapsed` and re-syncs.
#[derive(Debug, Clone)]
pub struct ToggleCollapseRequest {
    pub group: GroupId,
    pub collapsed: bool,
}

/// Fired when the user clicks the group header's delete affordance.
/// Host removes the [`Group`] from its model (members are NOT
/// affected — only the grouping is removed) and re-syncs.
#[derive(Debug, Clone)]
pub struct DeleteGroupRequest {
    pub group: GroupId,
}
