//! Node types — template (declarative) + instance (placed in editor).
//!
//! Per DIRECTIVE.md §4: a node is an INSTANCE of a TEMPLATE. The
//! template declares the component's ports + config schema; the
//! instance carries position, current config values, and host
//! metadata. The editor never hardcodes a node's fields — it renders
//! any node by walking its template.

use crate::config::ConfigSchema;
use crate::group::StatusBadge;
use crate::icon::NodeIcon;
use crate::port::{PortDesc, PortKind};
use blinc_core::layer::Point;
use std::sync::Arc;

// ─────────────────────────────────────────────────────────────────────
// NodeId
// ─────────────────────────────────────────────────────────────────────

/// Stable per-editor node identifier. Generated by the host (e.g. uuid,
/// reflow's `GraphNode.id`); the editor doesn't synthesise these.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct NodeId(pub Arc<str>);

impl NodeId {
    pub fn new(id: impl Into<Arc<str>>) -> Self {
        Self(id.into())
    }
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<&str> for NodeId {
    fn from(s: &str) -> Self {
        Self(Arc::from(s))
    }
}
impl From<String> for NodeId {
    fn from(s: String) -> Self {
        Self(Arc::from(s))
    }
}
impl From<Arc<str>> for NodeId {
    fn from(s: Arc<str>) -> Self {
        Self(s)
    }
}

// ─────────────────────────────────────────────────────────────────────
// NodeTemplate — declarative component description
// ─────────────────────────────────────────────────────────────────────

/// Visual shape of a node body. Borrowed from Zeal's `NodeShape`.
/// `Rectangle` is the default; `Circle` / `Diamond` suit
/// connector-style or decision-point nodes. `Custom` lets a host
/// supply its own renderer via the editor's renderer-override API;
/// builds without that hook fall back to `Rectangle`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
pub enum NodeShape {
    #[default]
    Rectangle,
    Circle,
    Diamond,
    /// Host supplies its own renderer for this shape via an editor
    /// override. Reserved variant.
    Custom,
}

/// Declarative description of a component. The palette renders one
/// entry per template; instances render from the template's port +
/// metadata layout.
///
/// `component` is the host's identifier for the underlying actor /
/// function / etc. (e.g. reflow's `GraphNode.component`). Two
/// instances of the same template share the same `component` string.
///
/// `category` groups templates in the palette (e.g. "data",
/// "control", "media") — host-defined, opaque to the editor.
#[derive(Clone)]
pub struct NodeTemplate<K: PortKind> {
    pub component: String,
    pub category: String,
    pub display_name: String,
    /// Subtitle the palette + node-body renderer surface beneath
    /// `display_name`. `None` = no subtitle. Equivalent to Zeal's
    /// `NodeMetadata.subtitle` (e.g. "Read Data", "Commit History").
    pub subtitle: Option<String>,
    pub inputs: Vec<PortDesc<K>>,
    pub outputs: Vec<PortDesc<K>>,
    /// Default shape for instances of this template. Per-instance
    /// override via [`NodeInstance::shape`].
    pub default_shape: NodeShape,
    /// Optional icon rendered in the node header. Construct via
    /// [`NodeIcon::from_svg_str`] from any SVG source — tabler,
    /// lucide, Material, custom markup. The editor parses once at
    /// template build time and renders via
    /// `blinc_svg::SvgDocument::render_fit`, so the same SVG works
    /// inside the canvas closure (unlike text, which is currently
    /// blocked upstream).
    pub icon: Option<NodeIcon>,
    /// Default variant token for the renderer (Zeal-style semantic
    /// colour role — `"primary"`, `"warning"`, `"surface"`, …).
    /// `None` = use the theme's default. Per-instance override via
    /// [`NodeInstance::variant`].
    pub default_variant: Option<String>,
    /// Strongly-typed schema description of the node's config
    /// fields — drives the inspector form. An empty schema means
    /// "no config" — no inspector pane shown. Per-variant validation
    /// (`required`, `min`/`max`, select options, …) lives on
    /// [`PropertyDefinition`](crate::config::PropertyDefinition);
    /// see [`crate::config::default_config`] /
    /// [`crate::config::validate`] for the host-side helpers.
    pub config_schema: ConfigSchema,
    /// Free-form template metadata — version, doc URL, recommended
    /// backend (per-host concept), etc. The palette can surface a
    /// subset; the editor itself doesn't read it.
    pub metadata: serde_json::Value,
    /// Optional content slot rendered inside the node body via
    /// [`blinc_portal_ui::Portal`]. Adds `content.height` pixels
    /// beneath the header; the closure paints into that region every
    /// frame using immediate-mode widgets. See
    /// [`Self::with_content`] for the builder + the portal-ui crate
    /// README for the widget surface.
    pub content: Option<NodeContent>,
}

/// Metadata-driven node content slot. See
/// [`NodeTemplate::with_content`].
#[derive(Clone)]
pub struct NodeContent {
    /// Body region height in pixels — added to the node's overall
    /// height. The portal paints inside a body rect of this height.
    pub height: f32,
    /// Per-frame UI closure. Receives the node id (for per-instance
    /// signal / state lookup) and a portal-ui builder; emit widgets
    /// or call `ui.allocate_painter(...)` for free-form painting.
    #[allow(clippy::type_complexity)]
    pub render: Arc<dyn Fn(&NodeId, &mut blinc_portal_ui::PortalUi) + Send + Sync>,
}

impl std::fmt::Debug for NodeContent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NodeContent")
            .field("height", &self.height)
            .field("render", &"<closure>")
            .finish()
    }
}

impl<K: PortKind> std::fmt::Debug for NodeTemplate<K>
where
    K: std::fmt::Debug,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NodeTemplate")
            .field("component", &self.component)
            .field("display_name", &self.display_name)
            .field("subtitle", &self.subtitle)
            .field("inputs", &self.inputs.len())
            .field("outputs", &self.outputs.len())
            .field("content", &self.content)
            .finish()
    }
}

impl<K: PortKind> NodeTemplate<K> {
    /// Minimal constructor — no config, no metadata. Used in tests
    /// and for the simplest "I just want a node with these ports"
    /// case.
    pub fn new(component: impl Into<String>, display_name: impl Into<String>) -> Self {
        Self {
            component: component.into(),
            category: String::new(),
            display_name: display_name.into(),
            subtitle: None,
            inputs: Vec::new(),
            outputs: Vec::new(),
            default_shape: NodeShape::default(),
            icon: None,
            default_variant: None,
            config_schema: ConfigSchema::new(),
            metadata: serde_json::Value::Null,
            content: None,
        }
    }

    /// Attach an immediate-mode UI rendered inside the node body.
    ///
    /// `height` is the body region's height in pixels (the node
    /// grows by this much beneath the header). `render` runs every
    /// frame inside [`blinc_portal_ui::Portal::frame`] — emit
    /// widgets (`ui.label`, `ui.slider_signal`, ...) or call
    /// `ui.allocate_painter(...)` for free-form painting (sparklines,
    /// sketch surfaces, custom visualisations).
    ///
    /// The closure receives the node id, useful for looking up
    /// per-instance state (signals keyed by node id, etc.). All
    /// portal state — widget interaction state in `PortalStorage`,
    /// signal subscriptions — is owned by the editor's per-node
    /// portal map.
    pub fn with_content<F>(mut self, height: f32, render: F) -> Self
    where
        F: Fn(&NodeId, &mut blinc_portal_ui::PortalUi) + Send + Sync + 'static,
    {
        self.content = Some(NodeContent {
            height,
            render: Arc::new(render),
        });
        self
    }

    pub fn with_category(mut self, category: impl Into<String>) -> Self {
        self.category = category.into();
        self
    }

    pub fn with_subtitle(mut self, subtitle: impl Into<String>) -> Self {
        self.subtitle = Some(subtitle.into());
        self
    }

    pub fn with_input(mut self, port: PortDesc<K>) -> Self {
        self.inputs.push(port);
        self
    }

    pub fn with_output(mut self, port: PortDesc<K>) -> Self {
        self.outputs.push(port);
        self
    }

    pub fn with_shape(mut self, shape: NodeShape) -> Self {
        self.default_shape = shape;
        self
    }

    pub fn with_icon(mut self, icon: NodeIcon) -> Self {
        self.icon = Some(icon);
        self
    }

    pub fn with_variant(mut self, variant: impl Into<String>) -> Self {
        self.default_variant = Some(variant.into());
        self
    }

    /// Set the typed config schema. Pass `vec![]` for "no config".
    pub fn with_config_schema(mut self, schema: ConfigSchema) -> Self {
        self.config_schema = schema;
        self
    }

    /// Append a single property to the schema. Convenience for
    /// builder chains that prefer one-property-per-line over
    /// constructing the whole `ConfigSchema` up front.
    pub fn with_property(mut self, property: impl Into<crate::config::PropertyDefinition>) -> Self {
        self.config_schema.properties.push(property.into());
        self
    }

    /// Append a reactive cascade rule to the schema.
    /// See [`crate::config::PropertyRule`].
    pub fn with_rule(mut self, rule: crate::config::PropertyRule) -> Self {
        self.config_schema.rules.push(rule);
        self
    }

    pub fn with_metadata(mut self, metadata: serde_json::Value) -> Self {
        self.metadata = metadata;
        self
    }
}

// ─────────────────────────────────────────────────────────────────────
// NodeInstance — a placed node in the editor's model
// ─────────────────────────────────────────────────────────────────────

/// A live node placed in the editor. References its template by
/// `component` name; the editor looks up the template at render time
/// to determine port positions and the inspector schema.
///
/// **Per-instance render overrides**: `shape`, `variant`, `icon`,
/// `subtitle` all default to `None` and fall back to the template's
/// defaults — useful when most instances of a template render
/// identically but a few want their own variant (e.g. a single
/// `HttpFetch` template instantiated as both "normal" and "critical"
/// styling per use).
///
/// `M` is the host metadata type — opaque to the editor. For nan8 +
/// reflow, this carries `GraphNode.metadata` (a `HashMap<String,
/// Value>` containing `dynasb.*` deploy state, `ExecutionSite`
/// backend, etc.). For other hosts, `M` can be `()`.
#[derive(Debug, Clone)]
pub struct NodeInstance<M> {
    pub id: NodeId,
    /// Template's `component` field. The editor uses this to look up
    /// the `NodeTemplate` at render time.
    pub component: String,
    /// Top-left corner in canvas-content coordinates. Updated as the
    /// user drags.
    pub position: Point,
    /// Logical size in content units. If `None`, the renderer uses
    /// the theme's default node size (per
    /// [`NodeEditorTheme`](crate::theme::NodeEditorTheme)).
    pub size: Option<(f32, f32)>,
    /// Per-instance shape override. `None` = template default.
    pub shape: Option<NodeShape>,
    /// Per-instance subtitle override. `None` = template subtitle.
    /// Useful for hosts that want to show e.g. the configured table
    /// name on a `PostgresQuery` instance rather than the generic
    /// template subtitle.
    pub subtitle: Option<String>,
    /// Per-instance theme variant token override. `None` = template
    /// default → theme default. Mirrors Zeal's per-instance variant.
    pub variant: Option<String>,
    /// Per-instance icon override. `None` = template icon. Same
    /// construction as [`NodeTemplate::icon`].
    pub icon: Option<NodeIcon>,
    /// Status badge rendered in the node's corner (Zeal-style chip).
    /// `None` = no badge. Hosts populate this from runtime state:
    /// "running", "errored last invocation", "validation issue".
    pub badge: Option<StatusBadge>,
    /// Current values for the template's `config_schema`. Free-form;
    /// the inspector reads + writes this.
    pub config: serde_json::Value,
    /// Host metadata for this node. The editor never reads this; it's
    /// the host's payload (e.g. reflow's `GraphNode.metadata`).
    pub metadata: M,
    /// Soft-disable flag. Hosts set this to mark a node as inactive
    /// without removing it from the graph (skipped during execution,
    /// excluded from runtime metrics, etc.). The renderer dims the
    /// node's body / header / icon / title and downgrades every
    /// incident edge to a faded "pending" style so the dataflow
    /// visually breaks at the disabled node. Defaults to `false`.
    pub disabled: bool,
    /// When `Some`, this node is a *subgraph reference* — a
    /// navigation entry-point into the named subgraph stored on the
    /// editor under this id. The renderer forces
    /// [`NodeShape::Diamond`] regardless of the template's
    /// `default_shape`, and a double-click emits
    /// [`crate::event::EditorEvent::SubgraphRequested`] for hosts to
    /// open / navigate into. Mirrors Zeal's `SubgraphNodeMetadata`
    /// pattern (`metadata.type === 'subgraph'`). `None` = regular
    /// node, no override.
    pub subgraph_ref: Option<crate::subgraph::SubgraphId>,
}

impl<M: Default> NodeInstance<M> {
    pub fn new(id: impl Into<NodeId>, component: impl Into<String>, position: Point) -> Self {
        Self {
            id: id.into(),
            component: component.into(),
            position,
            size: None,
            shape: None,
            subtitle: None,
            variant: None,
            icon: None,
            badge: None,
            config: serde_json::Value::Null,
            metadata: M::default(),
            disabled: false,
            subgraph_ref: None,
        }
    }
}

impl<M> NodeInstance<M> {
    pub fn with_subtitle(mut self, subtitle: impl Into<String>) -> Self {
        self.subtitle = Some(subtitle.into());
        self
    }

    pub fn with_shape(mut self, shape: NodeShape) -> Self {
        self.shape = Some(shape);
        self
    }

    pub fn with_variant(mut self, variant: impl Into<String>) -> Self {
        self.variant = Some(variant.into());
        self
    }

    pub fn with_icon(mut self, icon: NodeIcon) -> Self {
        self.icon = Some(icon);
        self
    }

    pub fn with_badge(mut self, badge: StatusBadge) -> Self {
        self.badge = Some(badge);
        self
    }

    pub fn with_size(mut self, width: f32, height: f32) -> Self {
        self.size = Some((width, height));
        self
    }

    /// Replace the host metadata. Useful when the host re-derives it
    /// from a backing store (reflow `GraphExport` re-loaded, etc.).
    pub fn with_metadata(mut self, metadata: M) -> Self {
        self.metadata = metadata;
        self
    }

    /// Apply a config patch. The editor doesn't merge — it overwrites.
    /// Hosts that want merge semantics should merge before passing in.
    pub fn with_config(mut self, config: serde_json::Value) -> Self {
        self.config = config;
        self
    }

    /// Flag the node as soft-disabled — see [`Self::disabled`].
    pub fn with_disabled(mut self, disabled: bool) -> Self {
        self.disabled = disabled;
        self
    }

    /// Mark this node as a subgraph reference — see
    /// [`Self::subgraph_ref`]. The renderer will force the diamond
    /// shape and the editor emits
    /// [`crate::event::EditorEvent::SubgraphRequested`] on
    /// double-click.
    pub fn with_subgraph_ref(mut self, sub: impl Into<crate::subgraph::SubgraphId>) -> Self {
        self.subgraph_ref = Some(sub.into());
        self
    }
}
